ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN apt-get update && apt-get install -y ros-humble-joint-state-publisher-gui
RUN rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y ros-humble-xacro
RUN rm -rf /var/lib/apt/lists/*

USER root
